# Generated by Django 6.0.4 on 2026-05-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topuporder',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='topuporder',
            name='paymongo_source_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='topuporder',
            name='qr_code_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topuporder',
            name='payment_method',
            field=models.CharField(choices=[('gcash', 'GCash'), ('bank', 'Bank Transfer'), ('cash', 'Cash Over the Counter'), ('paymaya', 'Maya'), ('card', 'Credit/Debit Card'), ('grab_pay', 'GrabPay')], default='gcash', max_length=20),
        ),
    ]
